# Generated by Django 6.0.2 on 2026-02-15 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsorteos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteo',
            name='creado_en',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='modificado_en',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
