# Generated by Django 6.0.2 on 2026-02-15 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsorteos', '0002_sorteo_creado_en_sorteo_modificado_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorteo',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='sorteo',
            name='modificado_en',
        ),
        migrations.AddField(
            model_name='sorteo',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sorteo',
            name='modificado_el',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
